### ISSUE TITLE
New User - Submit Error

### ISSUE THREAD

**Issue by tony-opp** [mike-webster/pet-tracker#25]
## Description
When trying to create a new user, the form does not submit after filling out info and clicking 'create user.'

![image](https://user-images.githubusercontent.com/30614663/73308435-e09e2c00-41e5-11ea-8b31-6402fd11a938.png)

**Comment by mike-webster** [comment]
@tony-opp Can you maybe try this again and try to include more information? I can't seem to be able to replicate the issue.  
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/25595930/73321842-4d76ed80-4209-11ea-97cf-7d404a53d279.gif)

**Comment by mike-webster** [comment]
If this is still an issue we can write it up with more details
