### ISSUE TITLE
Header - Front End

### ISSUE THREAD

**Issue by tony-opp** [mike-webster/pet-tracker#56]
## Description
Let's rework the Header and navigation menu's Front End so that the app name is in the top-left, and all nav options are top-right.

**Comment by tony-opp** [comment]
The header has been updated. 
- A placeholder app name is in the top-left, with all of the nav in the top-right
- Pets and Events nav options are functional drop-downs
- Mobile hamburger menu is functional

**Comment by mike-webster** [comment]
@tony-opp is that in a branch somewhere? Can you open a Pull Request so I can take a look?
